import { app, shell } from 'electron';
import { join } from 'path';
import { createWriteStream, existsSync, readFileSync, unlinkSync, writeFileSync } from 'fs';
import { tmpdir } from 'os';
import archiver from 'archiver';

/**
 * Publishing to nativeblade.dev. The Studio does the small part: device-code
 * login, list the account's apps, zip the project, and upload it against a
 * version. There is NO build trigger — the user clicks Build in the portal when
 * they want; the portal picks the last bundle the Studio uploaded + this
 * version.
 *
 *   login()  → device code → approve in browser → poll → access_token (stored)
 *   apps()   → GET /studio/apps                     (Bearer)
 *   upload() → POST /apps/{slug}/studio/uploads {version, env} → presigned PUT of the zip
 *
 * The .env goes up twice on purpose: inside the zip (where the build reads it)
 * and as `env`, which the backend uses to seed the app's env on FIRST publish
 * only — after that the portal owns it and publishing won't overwrite it.
 */

// Override for staging with NB_PUBLISH_BASE.
const BASE = process.env.NB_PUBLISH_BASE || 'https://nativeblade.dev/api/v1';

// Files that are regenerated by the build (or don't belong in an upload).
const IGNORE = [
    'node_modules/**', 'vendor/**', '.git/**', 'out/**', 'dist-wasm/**',
    'public/build/**', 'public/hot',
    'storage/framework/cache/**', 'storage/framework/sessions/**',
    'storage/framework/views/**', 'storage/logs/**',
    '**/.DS_Store',
];

const tokenFile = () => join(app.getPath('userData'), 'publish.json');

function getToken() {
    try { return JSON.parse(readFileSync(tokenFile(), 'utf-8')).access_token || null; }
    catch { return null; }
}

function saveToken(token) {
    writeFileSync(tokenFile(), JSON.stringify({ access_token: token }, null, 2));
}

export function publishStatus() {
    return { authenticated: !!getToken() };
}

export function publishLogout() {
    try { unlinkSync(tokenFile()); } catch { /* already gone */ }
    return { ok: true };
}

async function readJson(res) {
    try { return await res.json(); } catch { return {}; }
}

/**
 * OAuth 2.0 device flow. Emits `{ type: 'awaiting', userCode, url }` once the
 * browser is opened, then resolves when the user approves (or throws on
 * timeout). Field names follow the device-flow convention; adjust here if the
 * backend differs.
 */
export async function publishLogin({ emit } = {}) {
    const codeRes = await fetch(`${BASE}/device/code`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({}),
    });
    if (!codeRes.ok) throw new Error(`device/code failed (${codeRes.status})`);

    const data = await readJson(codeRes);
    const deviceCode = data.device_code;
    const url = data.verification_uri_complete || data.verification_uri;
    const interval = Math.max(2, Number(data.interval) || 5);
    const expiresIn = Number(data.expires_in) || 900;

    if (!deviceCode || !url) throw new Error('device/code returned an unexpected shape');

    emit?.({ type: 'awaiting', userCode: data.user_code || null, url });
    await shell.openExternal(url);

    const deadline = Date.now() + expiresIn * 1000;
    // Poll snappily (the endpoint has no rate limit) so the token is picked up
    // within a couple seconds of the user approving — not up to `interval` (5s).
    let wait = 2000;
    void interval;

    while (Date.now() < deadline) {
        await new Promise((r) => setTimeout(r, wait));

        const tokenRes = await fetch(`${BASE}/device/token`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ device_code: deviceCode }),
        });
        const body = await readJson(tokenRes);

        if (tokenRes.ok && body.access_token) {
            saveToken(body.access_token);
            return { ok: true };
        }
        if (body.error === 'slow_down') wait += 3000;
        else if (body.error && body.error !== 'authorization_pending') {
            throw new Error(body.error_description || body.error);
        }
        // authorization_pending → keep polling
    }

    throw new Error('login timed out — please try again');
}

/** GET /studio/apps → [{ slug, name }]. Clears the token on 401. */
export async function publishApps() {
    const token = getToken();
    if (!token) throw new Error('not authenticated');

    const res = await fetch(`${BASE}/studio/apps`, {
        headers: { Authorization: `Bearer ${token}` },
    });
    if (res.status === 401) { publishLogout(); throw new Error('unauthorized'); }
    if (!res.ok) throw new Error(`apps failed (${res.status})`);

    const data = await readJson(res);
    return data.apps || [];
}

/** Best-effort read of the app's current version from its provider. */
export function publishVersion(projectDir) {
    try {
        const src = readFileSync(join(projectDir, 'app/Providers/AppServiceProvider.php'), 'utf-8');
        const m = src.match(/->version\(\s*'([^']+)'/);
        return m ? m[1] : '1.0.0';
    } catch { return '1.0.0'; }
}

/** The project's local .env, if it has one. Seeds the app's env on first publish. */
function readEnvFile(projectDir) {
    try { return readFileSync(join(projectDir, '.env'), 'utf-8'); }
    catch { return null; }
}

function zipProject(dir) {
    return new Promise((resolve, reject) => {
        const out = join(tmpdir(), `nb-publish-${Date.now()}.zip`);
        const output = createWriteStream(out);
        const archive = archiver('zip', { zlib: { level: 9 } });

        output.on('close', () => resolve(out));
        archive.on('error', reject);
        archive.pipe(output);
        archive.glob('**/*', { cwd: dir, dot: true, ignore: IGNORE });
        archive.finalize();
    });
}

/**
 * Zip the project and upload it against `version`. Emits `{ type: 'zipping' }`
 * then `{ type: 'uploading' }`. Returns the saved version.
 */
export async function publishUpload({ slug, projectDir, version, emit } = {}) {
    const token = getToken();
    if (!token) throw new Error('not authenticated');
    if (!slug) throw new Error('no app selected');
    if (!existsSync(projectDir)) throw new Error('project folder not found');

    emit?.({ type: 'zipping' });
    const zip = await zipProject(projectDir);

    try {
        emit?.({ type: 'uploading' });

        // 1. presigned PUT + set this update's version (and seed the env if the
        // app has none yet).
        const u = await fetch(`${BASE}/apps/${slug}/studio/uploads`, {
            method: 'POST',
            headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
            body: JSON.stringify({ version, env: readEnvFile(projectDir) }),
        });
        if (u.status === 401) { publishLogout(); throw new Error('unauthorized'); }
        if (!u.ok) throw new Error(`upload request failed (${u.status})`);

        const { put_url, headers = {}, version: saved, env_seeded: envSeeded = false } = await readJson(u);
        if (!put_url) throw new Error('upload request returned no URL');

        // 2. push the zip straight to storage with the returned headers. Retry
        // on gateway/5xx errors (a Cloudflare/R2 502 is often transient); don't
        // retry 4xx (those are real request problems).
        const zipBuf = readFileSync(zip);
        let put;
        for (let attempt = 1; attempt <= 3; attempt++) {
            try {
                put = await fetch(put_url, { method: 'PUT', headers, body: zipBuf });
                if (put.ok || (put.status >= 400 && put.status < 500)) break;
            } catch (e) {
                if (attempt === 3) throw e;
            }
            if (attempt < 3) await new Promise((r) => setTimeout(r, 1500 * attempt));
        }
        if (!put.ok) {
            // Surface the storage error body + the target host so the real cause
            // (signature, endpoint, path-style, …) is visible.
            const detail = (await put.text().catch(() => '')).replace(/\s+/g, ' ').trim().slice(0, 300);
            let host = ''; try { host = new URL(put_url).host; } catch { /* ignore */ }
            throw new Error(`upload failed (${put.status}) to ${host}${detail ? ': ' + detail : ''}`);
        }

        return { ok: true, version: saved || version, envSeeded };
    } finally {
        try { unlinkSync(zip); } catch { /* temp file */ }
    }
}
